# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lister',
            name='image',
            field=models.ImageField(null=True, upload_to='car_image/'),
        ),
    ]
