# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191024_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lister',
            name='image',
            field=models.ImageField(upload_to='car_image/'),
        ),
    ]
