# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191024_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lister',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lister', to='app1.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
